config/routes.rb
NotifierHelper::Application.routes.draw do
  
  resources :notes

  devise_for :users
  
  root :to => "home#index" 
  resources :pages do
    member do
      post :pdf
    end
    collection do
      get :top
    end
    resources :comments
    resource :photo
  end
  
  resources :groups
  resources :notes
  resources :events do
    resources :notifications
  end
  resources :notifications do
    collection do
      post :add_contacts
      post :remove_contacts
      get :process_mails
    end
  end
  resources :contacts do
    collection do
      post :add_to_group
      post :remove_multiple
      post :get_by_group
      post :process_gmail
      get :response_gmail
    end
  end
  resources :profiles
  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validate :firstname, :presence => true, :message => 'Not valid'
  belongs_to :user
  has_and_belongs_to_many :groups
  has_many :receipient, :dependent => :destroy
  cattr_reader :per_page
  @@per_page = 10
  
  def fullname
    "#{firstname} #{lastname}"
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :notifications
end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :name, :description, :presence => true
  belongs_to :user
  has_and_belongs_to_many :contacts
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
  has_many :receipients
  
  def contacts
    current_contacts = []
    receipients.each do |el|
      current_contacts << el.contact
    end
    return current_contacts
  end
  
  def get_email_by_phonenumber(phonenumber) 
    result = ''
    phonenumber.gsub!("+", "")
    phonenumber.gsub!(" ", "")
    phonenumber.gsub!("-", "")
    phonenumber = phonenumber[1..phonenumber.length - 1] if phonenumber.start_with?('3')
    phonenumber = phonenumber[1..phonenumber.length - 1] if phonenumber.start_with?('8')
    code = phonenumber[0..2]
    p code
    case code
    when '067','096', '097', '098':
        result = '38' + phonenumber + '@2sms.kyivstar.net'      
    end
    
    return nil if result == ''
    return result
    
  end
  
  def process_all    
    process_emails
    process_free_sms
  end
  
  def process_emails
    
    receipients.each do |el|
      if(el.contact.email && el.contact.send_email)
        mail = Notifier.basic_message(el.contact.email, subject, body) 
        mail.deliver                    # sends the email
      end
    end
  end  
  
  def process_free_sms    
    receipients.each do |el|
      email_address = get_email_by_phonenumber(el.contact.phonenumber)
      if(email_address && el.contact.send_sms && el.contact.only_free_sms)
        mail = Notifier.basic_message(email_address, subject, sms_body)  # => a Mail::Message object
        mail.deliver                    # sends the email
      end
    end
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/receipient.rb
class Receipient < ActiveRecord::Base
  belongs_to :contact
  belongs_to :notification
  
    
  def fullname
    "#{contact.firstname} #{contact.lastname}"
  end
end

app/models/transporter.rb
class Transporter < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :contacts
  has_many :events
  has_many :groups
  has_many :notifications
  has_many :transporters
  has_many :notes
  has_one :profile
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /events
  # GET /events.xml
  def index
    @events = current_user.events.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = current_user.events.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = current_user.events.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = current_user.events.find(params[:id])
  end

  # POST /events
  # POST /events.xml
  def create
    @event = current_user.events.new(params[:event])
    if @event.save
      redirect_to(@event, :notice => 'Event was successfully created.')
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = current_user.events.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(@event, :notice => 'Event was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = current_user.events.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_filter :authenticate_user!
  # GET /notes
  # GET /notes.xml
  def index
    @notes = current_user.notes.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @notes }
    end
  end

  # GET /notes/1
  # GET /notes/1.xml
  def show
    @note = current_user.notes.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @note }
    end
  end

  # GET /notes/new
  # GET /notes/new.xml
  def new
    @note = current_user.notes.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @note }
    end
  end

  # GET /notes/1/edit
  def edit
    @note = current_user.notes.find(params[:id])
  end

  # POST /notes
  # POST /notes.xml
  def create
    @note = current_user.notes.new(params[:note])

    respond_to do |format|
      if @note.save
        format.html { redirect_to(@note, :notice => 'current_user.notes was successfully created.') }
        format.xml  { render :xml => @note, :status => :created, :location => @note }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @note.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.xml
  def update
    @note = current_user.notes.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to(@note, :notice => 'current_user.notes was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @note.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.xml
  def destroy
    @note = current_user.notes.find(params[:id])
    @note.destroy

    respond_to do |format|
      format.html { redirect_to(notes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NotifierHelper</title>
  <%= stylesheet_link_tag :all %>

  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"   %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.7/jquery-ui.min.js"   %>


  <%= javascript_include_tag "drag_n_drop_helper.js"  %>
  <%= javascript_include_tag "jquery-ui-timepicker-addon.js"  %>
  
  <%= javascript_include_tag "rails.js"  %>
  
  
  
  <%= csrf_meta_tag %>
  <%= stylesheet_link_tag  "style.css" %>
  <%= stylesheet_link_tag  "jquery-ui-1.8.7.custom.css" %>
  <%= formtastic_stylesheet_link_tag %>
  
  <!-- Reach editor section -->
  <!-- Skin CSS file -->
<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.8.2r1/build/assets/skins/sam/skin.css">
<!-- Utility Dependencies -->
<script src="http://yui.yahooapis.com/2.8.2r1/build/yahoo-dom-event/yahoo-dom-event.js"></script> 
<script src="http://yui.yahooapis.com/2.8.2r1/build/element/element-min.js"></script> 
<!-- Needed for Menus, Buttons and Overlays used in the Toolbar -->
<script src="http://yui.yahooapis.com/2.8.2r1/build/container/container_core-min.js"></script>
<script src="http://yui.yahooapis.com/2.8.2r1/build/menu/menu-min.js"></script>
<script src="http://yui.yahooapis.com/2.8.2r1/build/button/button-min.js"></script>
<!-- Source file for Rich Text Editor-->
<script src="http://yui.yahooapis.com/2.8.2r1/build/editor/editor-min.js"></script>
  
<script type="text/javascript">  
  $(document).ready(function(){ $('input.ui-date-picker').datetimepicker(); });
</script>  
  
</head>
<body class="yui-skin-sam">
  <div id="content">
    <div id="header">
      <%=render :partial=>"partials/menu"%>
      <div id="logo">Notifier Helper</div>      
    </div>
    <div id="main">
      <%= yield %>
    </div>
    <div id="footer">
      <hr/>
      &copy; 2010 
    </div>
  </div>
  
 
</body>
</html>

app/views/notifier/contact.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "contact" %>

app/views/partials/_menu.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>
<%if(current_user)%>
<div id="Menu">
  <table width="100%">
    <tr>
      <td width="50px">
        <%=link_to t(".groups"), groups_path, :class=>params[:controller] == "groups"  ? "selected" : ""  %>
      </td>
      <td width="60px">
        <%=link_to t(".contacts"), contacts_path, :class=>params[:controller] == "contacts"  ? "selected" : ""%>
      </td>
      <td width="50px">
        <%=link_to t(".events"), events_path, :class=>params[:controller] == "events"  ? "selected" : ""%>
      </td>     
      <td width="50px">
        <%=link_to t(".notifications"), notifications_path, :class=>params[:controller] == "notifications"  ? "selected" : ""%>
      </td>      
      <td></td>
      <td align="right" width="50px">
        <%=link_to t(".profile"), edit_profile_path(current_user.profile) %>
      </td> 
      <td align="right" width="50px">
        <%=link_to t(".logout"), destroy_user_session_path %>
      </td> 
    </tr>
  </table>
  <hr/>
</div>
<%end%>