config/routes.rb
NotifierHelper::Application.routes.draw do
  
  resources :notes

  devise_for :users
  
  root :to => "home#index" 
  resources :pages do
    member do
      post :pdf
    end
    collection do
      get :top
    end
    resources :comments
    resource :photo
  end
  
  resources :groups
  resources :notes
  resources :events do
    resources :notifications
  end
  resources :notifications do
    collection do
      post :add_contacts
      post :remove_contacts
      get :process_mails
    end
  end
  resources :contacts do
    collection do
      post :add_to_group
      post :remove_multiple
      post :get_by_group
      post :process_gmail
      get :response_gmail
    end
  end
  resources :profiles
  

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
  has_many :receipients
  
  def contacts
    current_contacts = []
    receipients.each do |el|
      current_contacts << el.contact
    end
    return current_contacts
  end
  
  def get_email_by_phonenumber(phonenumber) 
    result = ''
    phonenumber.gsub!("+", "")
    phonenumber.gsub!(" ", "")
    phonenumber.gsub!("-", "")
    phonenumber = phonenumber[1..phonenumber.length - 1] if phonenumber.start_with?('3')
    phonenumber = phonenumber[1..phonenumber.length - 1] if phonenumber.start_with?('8')
    code = phonenumber[0..2]
    p code
    case code
    when '067','096', '097', '098':
        result = '38' + phonenumber + '@2sms.kyivstar.net'      
    end
    
    return nil if result == ''
    return result
    
  end
  
  def process_all    
    process_emails
    process_free_sms
  end
  
  def process_emails
    
    receipients.each do |el|
      if(el.contact.email && el.contact.send_email)
        mail = Notifier.basic_message(el.contact.email, subject, body) 
        mail.deliver                    # sends the email
      end
    end
  end  
  
  def process_free_sms    
    receipients.each do |el|
      email_address = get_email_by_phonenumber(el.contact.phonenumber)
      if(email_address && el.contact.send_sms && el.contact.only_free_sms)
        mail = Notifier.basic_message(email_address, subject, sms_body)  # => a Mail::Message object
        mail.deliver                    # sends the email
      end
    end
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_filter :authenticate_user!
  
  before_filter :load_event
    
  def load_context
    @notification_context = @event ? [@event] : [] 
    @notification_context << @notification
    
  end
  
  def load_event
    if params[:event_id]
      @event = Event.find_by_id(params[:event_id])
    end 
  end
  
  # GET /notifications
  # GET /notifications.xml
  def index
    @notifications = current_user.notifications.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @notifications }
    end
  end

  # GET /notifications/1
  # GET /notifications/1.xml
  def show
    @notification = current_user.notifications.find(params[:id])
    @receipients = @notification.receipients.paginate(:page => params[:page] || 1, :per_page => 10)    

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @notification }
    end
  end

  # GET /notifications/new
  # GET /notifications/new.xml
  def new
    @notification = current_user.notifications.new
    load_context
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @notification }
    end
  end

  # GET /notifications/1/edit
  def edit
    @notification = current_user.notifications.find(params[:id])
    load_context
  end

  # POST /notifications
  # POST /notifications.xml
  def create
    @notification = current_user.notifications.new(params[:notification])
    @event = Event.find_by_id(params[:event_id]) if params[:event_id]
    @notification.event = @event if @event
    if @notification.save
      if @event
        redirect_to @event 
      else
        redirect_to(@notification, :notice => 'Notification was successfully created.')
      end        
    end
  end

  # PUT /notifications/1
  # PUT /notifications/1.xml
  def update
    @notification = current_user.notifications.find(params[:id])

    respond_to do |format|
      if @notification.update_attributes(params[:notification])
        format.html { redirect_to(@notification, :notice => 'Notification was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @notification.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.xml
  def destroy
    @notification = current_user.notifications.find(params[:id])
    @notification.destroy

    respond_to do |format|
      format.html { redirect_to(notifications_url) }
      format.xml  { head :ok }
    end
  end
  
  # POST /contacts
  # POST /contacts.xml
  def add_contacts    
    params[:contact_ids] = params[:contact_ids][0].split(', ')
    contacts = current_user.contacts.find(params[:contact_ids])    
    @notification = current_user.notifications.find(params[:id])
    
    contacts = contacts.collect{|el| @notification.contacts.include?(el) ? nil : el}.compact
    contacts.each do |el|
      @notification.receipients.create( :contact_id => el.id, :status => 'active' )
    end
     
    render :update do |page|      
      page.redirect_to(@notification)
    end  
  end  
  
  # POST /contacts
  def remove_contacts    
    params[:contact_ids] = params[:contact_ids].split(',')    
    contacts = current_user.contacts.find(params[:contact_ids])    
    if contacts    
      if params[:notification_id]
        notification = current_user.notifications.find(params[:notification_id])
        contacts = contacts.collect{|el| notification.contacts.include?(el) ? nil : el}.compact
        
        notification.receipients = notification.receipients - notification.receipients.where(:contact_id => params[:contact_ids])
        #redirect_to(contacts_path(:group_id => params[:group_id]), :notice => contacts.size.to_s + ' was successfully removed from' + group.name) 
        render :update do |page|
          page << "location.reload();"
        end      
      end
    end
    
  end 
  
  def process_mails
    notification = Notification.find_by_id(params[:notification_id])
    notification.process_all
    redirect_to(notification, :notice => 'Notification was successfully sended.')
    
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper

end

app/views/notifications/_form.html.erb
<div class="create_form">
  
<%= semantic_form_for @notification_context do |form| %>
    <%= form.inputs do %>
      <%= form.input :subject %>
      <%= form.input :body, :as => :text %>
      <%= form.input :sms_body, :as => :text %>
      <%= form.input :frequency,  :as => :select, :collection => ["one time", "daily", "weekends", "working days", "weekly", "monthly", "yearly"] %>
      <%= form.input :start_date, :as=>:date_picker  %>
      <%= form.input :end_date, :as=>:date_picker  %>
      <%= form.input :send_on, :as=>:date_picker  %>
      <%= form.input :status %>      
     
    <% end %>
    <% form.buttons do %>
      <%= form.commit_button %>
    <% end %>
  <% end %>
  
</div>

app/views/notifications/_list_item.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>
      <table class="ListItem">
        <tr>
          <td colspan="4" width="840px"><%= notification.subject %></td>
        </tr>
        <tr>
          <td width="600px" align="left" class="tag"><%= notification.body %></td>
          <td width="100px" align="left" class="tag"><%= notification.frequency %></td>
          <td width="90px" align="right" class="tag"><%= notification.start_date %></td>
          <td width="50px" align="right" class="tag"><%= notification.status %></td>
        </tr>
      </table>

app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<table>
  <tr>
    <td>
      <%= link_to t("common.add"), new_notification_path %>
    </td>
  </tr>
</table>
      

<table class="w100p borderT">
<% @notifications.each do |notification| %>
  <tr>
    <td><%= link_to render(:partial=>"notifications/list_item", :locals => {:notification => notification}), notification%></td>
    <td width="50px" align="right"><%= link_to t("common.edit"), edit_notification_path(notification) %></td>
    <td width="50px" align="right"><%= link_to t("common.delete"), notification, :confirm => t("common.are_you_sure"), :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/notifications/new.html.erb
<h1>New notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Subject:</b>
  <%= @notification.subject %>
</p>

<p>
  <b>Body:</b>
  <%= @notification.body %>
</p>

<p>
  <b>Sms body:</b>
  <%= @notification.sms_body %>
</p>

<p>
  <b>Frequency:</b>
  <%= @notification.frequency %>
</p>

<p>
  <b>Start date:</b>
  <%= @notification.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @notification.end_date %>
</p>

<p>
  <b>Status:</b>
  <%= @notification.status %>
</p>

<%= form_tag add_contacts_notifications_path, :remote => true, :onsubmit => 'prepare_data();' do %>
<p>
  <a href="#" onclick="$('#add_receipient').show('fast');">add receipient</a>
  <div id="add_receipient" class="popup" >    
    <input type="hidden" name="id" value="<%= @notification.id  %>"/>
      <table width="360px">
        <tr>
          <td colspan="2" >
            <select onchange="reload_contacts(this)" style="width: 200px">
              <option>Select group</option> 
              <option value="0">
               <%= t("common.all") %>
              </option> 
              <% current_user.groups.each do |group| %>
                <option value="<%=  group.id %>">
                  <%=  group.name %>
                </option>
              <% end %>              
            </select>
          </td>        
        </tr>
        <tr>
          <td align="left" colspan="2">
            <input name="filter" id="search_filter" type="text"  style="width: 200px">        
          </td>
        </tr>
        <tr>
          <td> 
            <div>            
              <%= render(:partial=>"contacts/contacts_for_notification", :locals => {:contacts => []})%>
            </div>
          </td>
          <td>
            <div>  
              <div class='dnd_panel'> 
              <p>Select: 
                  <a href='#' onclick='return $.dds.selectAll("list_2");'>all</a> 
                  <a href='#' onclick='return $.dds.selectNone("list_2");'>none</a> 
                  <a href='#' onclick='return $.dds.selectInvert("list_2");'>invert</a> 
              </p> 
              <ul id="list_2"> 
              </ul> 
              <input type="hidden" id='list_2_serialised' name="contact_ids[]" />
              </div>  
            </div>               
          </td>
        </tr>        
        <tr>
          <td align="left">
            <%= submit_tag t("common.add") %>
          </td>
          <td align="right">
            <input width="40px" type="button" value="cancel" onclick="$('#add_receipient').hide('fast');"  />
          </td>
        </tr>
      </table>

  </div>
<hr/>
</p>

  <%if @notification.contacts.size > 0 %>
  <p style="text-align:right;font-style: italic; color: gray;">    
    <b>has &nbsp; <%= @notification.contacts.size %> &nbsp; receipients</b>
    <hr/>
  </p>
  <%end%>

<p>
<div id="div_recipients">
  <%= will_paginate @receipients %>
  <table class="w100p">
    <%if @receipients.size > 0 %>
    <tr class="header_tr">
      <th>
        <input type="checkbox" id="checkAll" onclick="$('.checkbox_td input').attr('checked', $('#checkAll').is(':checked'));" />
      </th>      
      <th id="contact_actions" colspan="3" align="right">
        <div>
          <input type="button"
                 onclick="var val = []; 
                   $('.checkbox_td > input:checkbox:checked').each(function(i){val[i] = $(this).val() }); 
                   $.post('<%=remove_contacts_notifications_path%>?notification_id=<%= @notification.id %>&contact_ids=' + val );"
                   value="<%=t("common.remove_selected")%>"  
                   />
        </div>
      </th>
    </tr>
    <% end %>    
    <% @receipients.each do |rec| %>
      <% if rec.contact %>
      <tr>
        <td class="checkbox_td">
          <input type="checkbox"
                 name="contact_ids[]" 
                 id="contact_<%=rec.contact.id%>" 
                 value='<%= rec.contact.id %>'/>
        </td>
        <td class="w920">
          <%=  link_to render(:partial=>"contacts/list_item", :locals => {:contact => rec.contact}), rec.contact%>
        </td>
      </tr>
      <%end%>
    <% end %>
  </table>
  <%= will_paginate @receipients %>
</div>
</p>
<% end %>
<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %> |
<a href="<%=process_mails_notifications_path%>?notification_id=<%= @notification.id %>">Send</a>


<script type="text/javascript">
  function reload_contacts(l)
  {
    if(l.value > 0)
      $.post("<%=get_by_group_contacts_path%>?notification_id=<%= @notification.id  %>&group_id="+l.value);
    else if(l.value === '0')
      $.post("<%=get_by_group_contacts_path%>?notification_id=<%= @notification.id %>");
  }
  
  var My = {}     
  My.List = {
        Filter : function (inputSelector, listSelector) {

                // Sanity check  
                var inp, rgx = new RegExp(), titles = $(listSelector), keys;
                if (titles.length == 0) {
                        return false;
                }

                // The list with keys to skip (esc, arrows, return, etc)
                // 8 is backspace, you might want to remove that for better usability
                keys = [ 13, 27, 32, 37, 38, 39, 40];

                // binding keyup to the unordered list
                $(inputSelector).bind('keyup', function (e) {
                        if ($.inArray(e.keyCode, keys) >= 0) {
                                return false;
                        }

                        // Building the regex from our user input, 'inp' should be escaped
                        inp = $(this).attr('value');
                        rgx.compile(inp, 'im');
                        titles.each(function () {
                                if (rgx.source !== '' && !rgx.test($(this).html())) {
                                        $(this).hide();
                                } else {
                                        $(this).show();    
                                }
                        });
                });
        }
};

function init_filter(){
// When the DOM is ready
$(document).ready(function () {
        // Attach the filter to our input and list
        My.List.Filter('input#search_filter', '#list_1>li');
});
}

function prepare_data(){
  el = document.getElementById('list_2_serialised');
  el.value = el.textContent;
  $('#add_receipient').hide('fast');
  //$('#list_2_serialised').val($('#list_2_serialised').innerHTML);
}
  
link_lists();
  
 
  
</script>