config/routes.rb
NotifierHelper::Application.routes.draw do
  
  resources :notes

  devise_for :users
  
  root :to => "home#index" 
  resources :pages do
    member do
      post :pdf
    end
    collection do
      get :top
    end
    resources :comments
    resource :photo
  end
  
  resources :groups
  resources :notes
  resources :events do
    resources :notifications
  end
  resources :notifications do
    collection do
      post :add_contacts
      post :remove_contacts
      get :process_mails
    end
  end
  resources :contacts do
    collection do
      post :add_to_group
      post :remove_multiple
      post :get_by_group
      post :process_gmail
      get :response_gmail
    end
  end
  resources :profiles
  

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :notifications
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /events
  # GET /events.xml
  def index
    @events = current_user.events.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = current_user.events.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = current_user.events.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = current_user.events.find(params[:id])
  end

  # POST /events
  # POST /events.xml
  def create
    @event = current_user.events.new(params[:event])
    if @event.save
      redirect_to(@event, :notice => 'Event was successfully created.')
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = current_user.events.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(@event, :notice => 'Event was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = current_user.events.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="create_form">
  
  <script type="text/javascript">
    
    var myEditor = new YAHOO.widget.Editor('event_description', {
    height: '300px',
    width: '650px',
    dompath: true, //Turns on the bar at the bottom
    animate: true //Animates the opening, closing and moving of Editor windows
});
myEditor.render();
 
//Inside an event handler after the Editor is rendered
YAHOO.util.Event.on('event_submit', 'click', function() {
    //Put the HTML back into the text area
    myEditor.saveHTML();
 
    //The var html will now have the contents of the textarea
    var html = myEditor.get('element').value;
});
</script>
  
  <%= semantic_form_for @event do |form| %>
    <%= form.inputs do %>
      <%= form.input :title %>
      <div class="yui-skin-sam">
      <%= form.input :description, :as => :text %>
      </div>
      <%= form.input :start_date, :as=>:date_picker  %>
      <%= form.input :end_date, :as=>:date_picker %>
    <% end %>
    <% form.buttons do %>
      <%= form.commit_button %>      
    <% end %>
  <% end %>
    
</div>

app/views/events/_list_item.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>
      <table class="ListItem">
        <tr>
          <td colspan="2" width="840px"><%= event.title %></td>
        </tr>
        <tr>
          <td class="tag">
            <%= event.description.split[0..10] %>
          </td>
          <td width="100px" class="tag">
            <%= event.start_date %>
          </td>          
        </tr>
      </table>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<table>
  <tr>
    <td>
      <%= link_to t("common.add"), new_event_path %>
    </td>
  </tr>
</table>
      

<table class="w100p borderT">
<% @events.each do |event| %>
  <tr>
    <td><%= link_to render(:partial=>"events/list_item", :locals => {:event => event}), event%></td>
    <td width="50px" align="right"><%= link_to t("common.edit"), edit_event_path(event) %></td>
    <td width="50px" align="right"><%= link_to t("common.delete"), event, :confirm => t("common.are_you_sure"), :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p class="title">
  <%= @event.title %>
</p>
<p>
  <b>Date:</b>
  <%= @event.start_date %>
  <hr/>
</p>

<p>  
  <%= raw (@event.description) %>
</p>

<%= link_to t("common.add_notification"), new_event_notification_path(:event_id => @event.id) %>
<table class="w100p borderT">
<% @event.notifications.each do |notification| %>
  <tr>
    <td><%= link_to render(:partial=>"notifications/list_item", :locals => {:notification => notification}), notification%></td>
    <td width="50px" align="right"><%= link_to t("common.edit"), edit_notification_path(notification) %></td>
    <td width="50px" align="right"><%= link_to t("common.delete"), notification, :confirm => t("common.are_you_sure"), :method => :delete %></td>
  </tr>
<% end %>
</table>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>