config/routes.rb
NotifierHelper::Application.routes.draw do
  
  resources :notes

  devise_for :users
  
  root :to => "home#index" 
  resources :pages do
    member do
      post :pdf
    end
    collection do
      get :top
    end
    resources :comments
    resource :photo
  end
  
  resources :groups
  resources :notes
  resources :events do
    resources :notifications
  end
  resources :notifications do
    collection do
      post :add_contacts
      post :remove_contacts
      get :process_mails
    end
  end
  resources :contacts do
    collection do
      post :add_to_group
      post :remove_multiple
      post :get_by_group
      post :process_gmail
      get :response_gmail
    end
  end
  resources :profiles
  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validate :firstname, :presence => true, :message => 'Not valid'
  belongs_to :user
  has_and_belongs_to_many :groups
  has_many :receipient, :dependent => :destroy
  cattr_reader :per_page
  @@per_page = 10
  
  def fullname
    "#{firstname} #{lastname}"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :contacts
  has_many :events
  has_many :groups
  has_many :notifications
  has_many :transporters
  has_many :notes
  has_one :profile
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_filter :authenticate_user!
  # GET /contacts
  # GET /contacts.xml
  def index
    
    if(params[:group_id])
      @contacts = current_user.groups.find(params[:group_id]).contacts.paginate(:page => params[:page] || 1, :per_page => 10)
    else
      @contacts = current_user.contacts.paginate(:page => params[:page] || 1, :per_page => 10)
    end

  end

  # GET /contacts/1
  # GET /contacts/1.xml
  def show
    @contact = current_user.contacts.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.xml
  def new
    @contact = current_user.contacts.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @contact }
    end
  end

  # GET /contacts/1/edit
  def edit
    @contact = current_user.contacts.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.xml
  def create
    @contact = current_user.contacts.new(params[:contact])

    respond_to do |format|
      if @contact.save
        format.html { redirect_to(@contact, :notice => 'current_user.contacts was successfully created.') }
        format.xml  { render :xml => @contact, :status => :created, :location => @contact }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @contact.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # POST /contacts
  # POST /contacts.xml
  def add_to_group
    if(params[:group_id] && params[:group_id].to_s.length > 0 && params[:contact_ids] && params[:contact_ids].to_s.length > 0)
      contacts = current_user.contacts.find(params[:contact_ids])    
      group = current_user.groups.find(params[:group_id])
      contacts = contacts.collect{|el| group.contacts.include?(el) ? nil : el}.compact
      group.contacts << contacts
      redirect_to(contacts_path, :notice => contacts.size.to_s + ' was successfully added to' + group.name) 
    else
      redirect_to contacts_path
    end
    
  end
  
  # POST /contacts
  # POST /contacts.xml
  def remove_multiple    
    params[:contact_ids] = params[:contact_ids].split(',')    
    contacts = current_user.contacts.find(params[:contact_ids])    
    if contacts    
      if params[:group_id]
        group = current_user.groups.find(params[:group_id])
        contacts = contacts.collect{|el| group.contacts.include?(el) ? nil : el}.compact
        
        group.contacts = group.contacts - group.contacts.where(:id => params[:contact_ids])
        #redirect_to(contacts_path(:group_id => params[:group_id]), :notice => contacts.size.to_s + ' was successfully removed from' + group.name) 
        render :update do |page|
          page << "location.reload();"
        end
        
      else  
        current_user.contacts.where(:id => params[:contact_ids]).destroy_all
        #redirect_to(contacts_path, :notice => contacts.size.to_s  + ' was successfully removed ') 
        render :update do |page|
          page << "location.reload();"
        end        
      end
    end
    
  end  

  # PUT /contacts/1
  # PUT /contacts/1.xml
  def update
    @contact = current_user.contacts.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to(@contact, :notice => 'current_user.contacts was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @contact.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.xml
  def destroy
    @contact = current_user.contacts.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to(contacts_url) }
      format.xml  { head :ok }
    end
  end
  
  def process_gmail
    if params['email'] && params['email'].to_s.length > 0
      gmail_contacts = GmailContacts.new
      redirect_url = response_gmail_contacts_path(:email => params['email'], :group_id => params['group_id'], :group_name => params['group_name'], :only_path => false)
      redirect_to gmail_contacts.authsub_url(redirect_url)
      
    else
      redirect_to contacts_path
    end
  end
  
  def response_gmail
    importer = GmailContacts.new(params["token"].to_s)
    importer.fetch params["email"]
    
    if (importer.contacts.size > 0)
      if(params["group_id"] && params["group_id"].to_i > 0)
        group = current_user.groups.find(params[:group_id])
      else if (params["group_id"] && params["group_id"].to_i == -1 && params["group_name"] && params["group_name"].to_s.length > 0)
          current_user.groups.create(:name => params["group_name"], :description => "Imported contacts from Gmail.")
          group = current_user.groups.find_by_name(params["group_name"])  
      else      
        current_user.groups.create(:name => "Gmail contacts:" + params["email"] , :description => "Imported contacts from Gmail.")
        group = current_user.groups.find_by_name("Gmail contacts:" + params["email"])
      end
      end
      importer.contacts.each do |contact|
         #{:email=>contact.emails.first, :title=>contact.}

         if(contact)
           if(current_user.contacts.where(:email => contact.emails.first).size > 0)
             group.contacts << current_user.contacts.where(:email => contact.emails.first)
           else
           
             contact.title.gsub(",", " ")
             contact.title.gsub("@", " ")
             first_name = contact.title.split(" ")[0]
             unless(contact.title.include?("@")) 
               last_name = contact.title.split(" ")[1]
             end
             unless(first_name)
               first_name = contact.emails.first.split("@")[0]
             end
             group.contacts.create(:user_id => current_user.id, :firstname => first_name, :lastname => last_name, :email => contact.emails.first, :phonenumber => contact.phone_numbers.first)
           end
         end
      end
    end
    
    redirect_to contacts_path(:group_id => group.id)
  end
  
  def get_by_group
    notification = Notification.find_by_id(params[:notification_id])
    if params[:group_id]
      @contacts = Group.find_by_id(params[:group_id]).contacts 
    else
      @contacts = current_user.contacts
    end
    
    @contacts = @contacts.collect{|el| notification.contacts.include?(el) ? nil : el}.compact    
    render :update do |page|
      page.replace_html :contacts_div, :partial => "contacts_for_notification", :locals => {:contacts => @contacts}     
      page << "link_lists();init_filter();"
    end
  end
  
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_contacts_for_notification.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<div id="contacts_div">
        <div class='dnd_panel'> 
        <p>Select: 
            <a href='#' onclick='return $.dds.selectAll("list_1");'>all</a> 
            <a href='#' onclick='return $.dds.selectNone("list_1");'>none</a> 
            <a href='#' onclick='return $.dds.selectInvert("list_1");'>invert</a> 
        </p> 

        <ul id="list_1"> 
            <% contacts.each do |contact| %>
              <li id="<%= contact.id%>"><%= contact.fullname %></li> 
            <%end%>      
        </ul> 
        <span id='list_1_serialised'></span> 
        </div>           



</div>

app/views/contacts/_form.html.erb
<div class="create_form">

  <%= semantic_form_for @contact do |form| %>
    <%= form.inputs do %>
      <%= form.input :firstname %>
      <%= form.input :lastname %>
      <%= form.input :email %>
      <%= form.input :phonenumber %>
      <%= form.input :fb_id %>
      <%= form.input :vk_id %>
      <%= form.input :comment, :as => :text %>
      <%= form.input :send_email %>
      <%= form.input :send_sms %>
      <%= form.input :only_free_sms %>
      <%= form.input :groups, :as => :check_boxes, :collection => current_user.groups.find(:all, :order => "name ASC") %>
    <% end %>
    <% form.buttons do %>
      <%= form.commit_button %>
    <% end %>
  <% end %>
  
</div>

app/views/contacts/_list_item.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>
      <table class="ListItem w100p">
        <tr>
          <td width="25%"><%= contact.fullname %></td>
          <td width="25%"><%= contact.comment %></td>
          <td width="25%"><%= contact.email %></td>
          <td width="15%"><%= contact.phonenumber %></td>   
          <td width="5%">
            <%if contact.send_email %>
              <img src="/images/icons/email.png" width="20px"/>
            <%end%>
          </td>
          <td width="5%">
            <%if contact.send_email %>
              <img src="/images/icons/phone.png"  width="20px"/>
            <%end%>
          </td>                   
        </tr>
        <tr>
          <td colspan="6" class="tag">
            <% contact.groups.each do |group| %>
            (
            <%= group.name %>
            )&nbsp;&nbsp;&nbsp;
            <%end%>
          </td>
        </tr>
      </table>

app/views/contacts/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<div id="leftMenu">
  <div>
    <b>Groups</b>
    <hr/>
    <ul>
      <li>
       <%= link_to t("common.all"), contacts_path, :class => params[:group_id] ? "" : "selected"   %>
      </li> 
      <% current_user.groups.each do |group| %>
        <li>
          <%= link_to group.name, contacts_path(:group_id => group.id), :class => params[:group_id].to_i == group.id  ? "selected" : "" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<div id="rightContent">    
    <table>
      <tr>
        <td>
          <%= link_to t("common.add"), new_contact_path %>
        </td>
        <td>|</td>
        <td>
          <a href="#" onclick="$('#import_gmail').show('fast');">import from gmail</a>
          <div id="import_gmail" class="popup" >
            <%= form_tag process_gmail_contacts_path do %>
              <table width="150px">
                <tr>
                  <td>
                    Email:
                  </td> 
                  <td>
                    <input type="text" name="email" width="140px"/>
                  </td>
                </tr>
                <tr>
                  <td>    
                    Group:
                  </td>                   
                  <td colspan="2">
                    <select name="group_id" id="select_group_id" onchange="$('#select_group_id').val() == -1 ? $('#div_group_name').show() : $('#div_group_name').hide();">
                      <% current_user.groups.each do |group| %>
                      <option value="<%= group.id%>">
                        <%= group.name%>
                      </option>
                      <% end %>
                      <option value="-1">
                        Create new
                      </option>
                    </select>
                  </td>
                </tr                
                <tr>                  
                  <td colspan="2">
                    <div id="div_group_name" class="dnd">
                      <input type="text" name="group_name" width="140px"/>
                    </div>
                  </td>
                </tr>                
                <tr>
                  <td align="left">
                    <%= submit_tag t("common.add") %>
                  </td>
                  <td align="right">
                    <input width="40px" type="button" value="cancel" onclick="$('#import_gmail').hide('fast');"  />
                  </td>
                </tr>
              </table>
            <% end %>
            </div>
        </td>
      </tr>
    </table>
    <%= form_tag add_to_group_contacts_path do %>
    <%= will_paginate @contacts %>
    <table cellspacing="0">
      <%if @contacts.size > 0 %>
      <tr class="header_tr">
        <th>
          <input type="checkbox" id="checkAll" onclick="$('.checkbox_td input').attr('checked', $('#checkAll').is(':checked'));" />
        </th>      
        <th id="contact_actions" colspan="3" align="right">
          <div>
            <%=t("common.selected_to")%>   
            <select name="group_id">
              <% current_user.groups.each do |group| %>
              <option value="<%= group.id%>">
                <%= group.name%>
              </option>
              <% end %>
            </select>
           
            <%= submit_tag t("common.add") %>
            <input type="button"
                   onclick="var val = []; 
                     $('.checkbox_td > input:checkbox:checked').each(function(i){val[i] = $(this).val() }); 
                     $.post('<%=remove_multiple_contacts_path%>?contact_ids=' + val );"
                     value="<%=t("common.delete_permanently")%>"  
                     />
            <% if params[:group_id] %>
            <input type="button"
                   onclick="var val = []; 
                     $('.checkbox_td > input:checkbox:checked').each(function(i){val[i] = $(this).val() }); 
                     $.post('<%=remove_multiple_contacts_path%>?group_id=<%=params[:group_id]%>&contact_ids=' + val );"
                     value="<%=t("common.delete_from_group")%>"  
                     />
            <% end %>

          </div>
        </th>
      </tr>
      <% end %>
    <% @contacts.each do |contact| %>
      <tr>
        <td class="checkbox_td">
          <input type="checkbox"
                 name="contact_ids[]" 
                 id="contact_<%=contact.id%>" 
                 value='<%= contact.id %>'
                 />
        </td>
        <td class="w600">
          <%=  link_to render(:partial=>"contacts/list_item", :locals => {:contact => contact}), contact%>
        </td>
        <td width="50px" align="right"><%= link_to t("common.edit"), edit_contact_path(contact) %></td>
        <td width="50px" align="right"><%= link_to t("common.delete"), contact, :confirm => t("common.are_you_sure"), :method => :delete %></td>
      </tr>
    <% end %>
    </table>
  <%= will_paginate @contacts %>
  <% end %>
  <br />  
</div>

app/views/contacts/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<div class="content_panel">
  <p id="notice"><%= notice %></p>
  <div class="show">    
    <p class="title">
      <%= @contact.fullname %>
    </p>
    <p class="comment">
      <%= @contact.comment %>
    </p>    
    <hr/>
    <table width="100%">
      <tr>
        <td width="50px">
          <img src="/images/icons/email.png"/>
        </td>
        <td>
          <%= @contact.email %>
        </td>
      </tr>
      <% if @contact.phonenumber %>            
      <tr>
        <td width="50px">
          <img src="/images/icons/phone.png"/>
        </td>
        <td>
          <%= @contact.phonenumber %>
        </td>
      </tr>
      <% end %>
      <% if @contact.fb_id %>      
      <tr>
        <td width="50px">
          <img src="/images/icons/facebook.png"/>
        </td>
        <td>
          <a href="http://www.facebook.com/profile.php?id=<%= @contact.fb_id %>"><%= @contact.fb_id %></a>
        </td>
      </tr>      
      <% end %>
      <% if @contact.vk_id %>      
      <tr>
        <td width="50px">
          <img src="/images/icons/vk.png"/>
        </td>
        <td>          
            <a href="http://vk.com/id<%= @contact.vk_id %>"><%= @contact.vk_id %></a>
        </td>
      </tr>      
      <% end %>
    </table>
    <hr/>
    <p>
      <b>Send email:</b>
      <%= @contact.send_email %>
    </p>

    <p>
      <b>Send sms:</b>
      <%= @contact.send_sms %>
    </p>

    <p>
      <b>Only free sms:</b>
      <%= @contact.only_free_sms %>
    </p>
    <hr/>
    <% if @contact.groups.size > 0 %>
    <b>belongs to groups: &nbsp;&nbsp;&nbsp;<b/>
    <span class="tag">
      <% @contact.groups.each do |group| %>
      (
      <%= group.name %>
      )&nbsp;&nbsp;&nbsp;
      <%end%>
    </span>
    <hr/>
    <%end%>
  </div>

  <%= link_to t("common.edit"), edit_contact_path(@contact) %> |
  <%= link_to t("common.back"), contacts_path %>
</div>